// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // マイグレーション: Session pooler (5432) — shadow DB作成が安定
    // アプリ実行: Transaction pooler (6543) — src/lib/db/prisma.ts で DATABASE_URL を使用
    // MIGRATE_DATABASE_URL (ローカル .env) または DIRECT_URL (Vercel) を優先使用
    url: process.env["MIGRATE_DATABASE_URL"] ?? process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
