ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "lineProjectId" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "utmSource" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "utmMedium" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "utmCampaign" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "utmContent" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "utmTerm" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "metaAdId" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "metaAdsetId" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "metaCampaignId" TEXT;
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "metaAdAccountId" TEXT;
CREATE INDEX IF NOT EXISTS "Contact_tenantId_utmSource_idx" ON "Contact"("tenantId", "utmSource");
CREATE INDEX IF NOT EXISTS "Contact_tenantId_metaCampaignId_idx" ON "Contact"("tenantId", "metaCampaignId");
ALTER TABLE "Contact" ADD CONSTRAINT "Contact_lineProjectId_fkey" FOREIGN KEY ("lineProjectId") REFERENCES "LineProject"("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE IF NOT EXISTS "MetaAdsAccount" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "name" TEXT NOT NULL, "adAccountId" TEXT NOT NULL, "accessToken" TEXT NOT NULL, "pixelId" TEXT, "businessId" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT TRUE, "lastSyncedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MetaAdsAccount_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "MetaAdsAccount_tenantId_adAccountId_key" ON "MetaAdsAccount"("tenantId", "adAccountId");
CREATE INDEX IF NOT EXISTS "MetaAdsAccount_tenantId_idx" ON "MetaAdsAccount"("tenantId");
ALTER TABLE "MetaAdsAccount" ADD CONSTRAINT "MetaAdsAccount_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE IF NOT EXISTS "MetaAdsCampaignStat" ("id" TEXT NOT NULL, "accountId" TEXT NOT NULL, "date" DATE NOT NULL, "campaignId" TEXT NOT NULL, "campaignName" TEXT NOT NULL, "adsetId" TEXT, "adsetName" TEXT, "adId" TEXT, "adName" TEXT, "impressions" INTEGER NOT NULL DEFAULT 0, "clicks" INTEGER NOT NULL DEFAULT 0, "spend" DOUBLE PRECISION NOT NULL DEFAULT 0, "reach" INTEGER NOT NULL DEFAULT 0, "leads" INTEGER NOT NULL DEFAULT 0, "purchases" INTEGER NOT NULL DEFAULT 0, "revenue" DOUBLE PRECISION NOT NULL DEFAULT 0, "utmContacts" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MetaAdsCampaignStat_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "MetaAdsCampaignStat_unique_idx" ON "MetaAdsCampaignStat"("accountId", "date", "campaignId", COALESCE("adsetId", ''), COALESCE("adId", ''));
CREATE INDEX IF NOT EXISTS "MetaAdsCampaignStat_accountId_idx" ON "MetaAdsCampaignStat"("accountId");
CREATE INDEX IF NOT EXISTS "MetaAdsCampaignStat_accountId_date_idx" ON "MetaAdsCampaignStat"("accountId", "date");
CREATE INDEX IF NOT EXISTS "MetaAdsCampaignStat_campaignId_idx" ON "MetaAdsCampaignStat"("campaignId");
ALTER TABLE "MetaAdsCampaignStat" ADD CONSTRAINT "MetaAdsCampaignStat_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "MetaAdsAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
